# Generated by Django 4.2.3 on 2024-01-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city_village_master_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_village_id', models.IntegerField(default=0)),
                ('district_id', models.IntegerField(default=0)),
                ('state_id', models.IntegerField(default=0)),
                ('city_village_name', models.TextField()),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by_user_id', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'city_village_master_table',
            },
        ),
    ]
