# Generated by Django 4.2.3 on 2024-01-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_city_village_master_table_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='gstcharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst_char_id', models.IntegerField(default=0)),
                ('year', models.TextField()),
                ('cgst_per', models.FloatField(default=0, null=True)),
                ('sgst_per', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'gstcharges',
            },
        ),
    ]
