# Generated by Django 4.2.3 on 2024-01-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='CityVillageMaster',
        ),
        migrations.DeleteModel(
            name='ComplainMaster',
        ),
        migrations.DeleteModel(
            name='ComplainStatus',
        ),
        migrations.DeleteModel(
            name='DistrictMaster',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DocDetail',
        ),
        migrations.DeleteModel(
            name='DocMaster',
        ),
        migrations.DeleteModel(
            name='DocVehDetailsTable',
        ),
        migrations.DeleteModel(
            name='gstcharges',
        ),
        migrations.DeleteModel(
            name='PaymentMaster',
        ),
        migrations.DeleteModel(
            name='ReviewFeedback',
        ),
        migrations.DeleteModel(
            name='ReviewFeedbackStatus',
        ),
        migrations.DeleteModel(
            name='StateMasterTable',
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
        migrations.DeleteModel(
            name='UserMasterTable',
        ),
        migrations.DeleteModel(
            name='VehicleMaster',
        ),
        migrations.DeleteModel(
            name='VehicleRoutMaster',
        ),
        migrations.DeleteModel(
            name='VehRoutDetalis',
        ),
    ]
