# Generated by Django 4.2.3 on 2024-01-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0007_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content_type_id', models.IntegerField()),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('permission_id', models.IntegerField()),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityVillageMaster',
            fields=[
                ('city_village_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_village_name', models.TextField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'city_village_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplainMaster',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_description', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'complain_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplainStatus',
            fields=[
                ('com_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_status_date', models.DateField(blank=True, null=True)),
                ('com_status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'complain_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictMaster',
            fields=[
                ('district_id', models.IntegerField(primary_key=True, serialize=False)),
                ('district_name', models.TextField(blank=True, null=True)),
                ('description', models.CharField(max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'district_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('content_type_id', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocDetail',
            fields=[
                ('doc_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_address', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_weight', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'doc_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocMaster',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_number', models.IntegerField(blank=True, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('lr_number', models.IntegerField(blank=True, db_column='LR_number', null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('is_cancel', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'doc_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocVehDetailsTable',
            fields=[
                ('doc_veh_det_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'doc_veh_details_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gstcharges',
            fields=[
                ('gst_char_id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.TextField(blank=True, null=True)),
                ('cgst_per', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('sgst_per', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'gstcharges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('doc_pay_detail', models.TextField(blank=True, null=True)),
                ('doc_pay_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pay_status', models.TextField(blank=True, null=True)),
                ('pay_method', models.TextField(blank=True, null=True)),
                ('pay_tran_id', models.IntegerField(blank=True, null=True)),
                ('pay_response', models.TextField()),
            ],
            options={
                'db_table': 'payment_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewFeedback',
            fields=[
                ('review_id', models.IntegerField(db_column='Review_id', primary_key=True, serialize=False)),
                ('review_image', models.CharField(db_column='Review_image', max_length=10)),
                ('review_description', models.TextField(db_column='Review_description')),
                ('review_star', models.IntegerField(db_column='Review_star')),
            ],
            options={
                'db_table': 'review&feedback',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReviewFeedbackStatus',
            fields=[
                ('review_status_id', models.IntegerField(db_column='Review_status_id', primary_key=True, serialize=False)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review&feedback_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateMasterTable',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stat_name', models.TextField(blank=True, null=True)),
                ('description', models.CharField(db_column='Description', max_length=50)),
                ('created_date', models.DateField()),
                ('updated_date', models.DateField()),
            ],
            options={
                'db_table': 'state_master_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_deatil_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_type', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.TextField()),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('address', models.TextField(blank=True, db_column='Address', null=True)),
            ],
            options={
                'db_table': 'user_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMasterTable',
            fields=[
                ('user_master_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email_id', models.TextField()),
                ('user_name', models.TextField()),
                ('user_password', models.TextField()),
            ],
            options={
                'db_table': 'user_master_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('vehicle_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehicle_name', models.TextField()),
                ('rc_book_number', models.CharField(blank=True, db_column='RC_book_number', max_length=50, null=True)),
                ('reg_no', models.IntegerField(blank=True, db_column='Reg_no', null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('insurance_from', models.DateTimeField(blank=True, null=True)),
                ('insurance_to', models.DateTimeField(blank=True, null=True)),
                ('insurance_company_name', models.TextField(blank=True, null=True)),
                ('owner_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleRoutMaster',
            fields=[
                ('veh_rout_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vehc_rout_det', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_rout_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehRoutDetalis',
            fields=[
                ('veh_rout_det_id', models.IntegerField(primary_key=True, serialize=False)),
                ('decription', models.TextField()),
                ('char_bel_50', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('char_bel_150', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('char_abo_150', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'veh_rout_detalis',
                'managed': False,
            },
        ),
    ]
