# Generated by Django 4.2.3 on 2024-03-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_master_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email_id', models.TextField()),
                ('user_name', models.TextField()),
                ('user_password', models.TextField()),
            ],
        ),
    ]
