# Generated by Django 4.2.3 on 2024-04-25 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorderform1',
            fields=[
                ('doc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doc_number', models.IntegerField(blank=True, null=True)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('lr_number', models.IntegerField(blank=True, db_column='LR_number', null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'doc_master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMasterTable1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_id', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_master_table',
                'managed': False,
            },
        ),
    ]
